### ISSUE TITLE
Badge PR opened for repo which has had room for months

### ISSUE THREAD

**Issue by trishume** [gitterHQ/readme-badger#11]
See https://github.com/syl20bnr/spacemacs/pull/2682

Spacemacs has had an active room for months, one created by the owner.
It seems someone managed to cause a creation event despite the room already existing.

It also seems to have used an old readme as a base.

**Comment by MadLittleMods** [comment]
Hey @trishume,

We had a security hiccup in our API which allowed anyone to send out the badger and make a PR. We rolled out a fix and the button is only visible to users with admin permissions(for a repo, someone with push access) for that room.

It looks like the UI guided the user and they went in the ["Share this chat room" modal and clicked the "Send Pull Request" button](http://i.imgur.com/QEwZoBP.png).
