### ISSUE TITLE
gitter-badger missed!

### ISSUE THREAD

**Issue by quat1024** [gitterHQ/readme-badger#12]
https://github.com/ElementalCode/Elemental/blob/0e14a591371fb8d88b5df53587302a6b1e01cfdb/README.md

The bot picked a... pretty bad spot for the badge in our project, hehe. Here's where I would have put it: https://github.com/ElementalCode/Elemental/blob/5e334e023665c8b488644d2eb864505dd95c31b8/README.md . Thought I'd let you know.

Could at least use a newline after the badge so it doesn't make the text flow around it and look weird :)

**Comment by MadLittleMods** [comment]
Thank you for the test case :)

gitterHQ/readme-badger#10 wouldwork nicely to suss out these tricky situations.

**Comment by trotha01** [comment]
It said to let you know if it missed and pointed me to issues. This looked like the most relevant issue.

It added the badge under the title "Example"
https://github.com/gitter-badger/elm-material/commit/42aeac94d5462e2b5e25f740d7744a0675499dc4?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
