### ISSUE TITLE
How to undo opting out for badger PRs

### ISSUE THREAD

**Issue by tiesmaster** [gitterHQ/readme-badger#13]
I accidentally pressed the link to opt out for automatic PRs from gitter. How do I undo that?

**Comment by MadLittleMods** [comment]
You can click the wrench and screw driver icon in the top right in your room -> Share this chat room -> Send  pull request button on the modal that pops up.

![](http://i.imgur.com/Q9sBXMW.png)

![](http://i.imgur.com/nlBNVMB.png)

**Comment by tiesmaster** [comment]
Nice!! Thanks, I'm going to try that ;)
