### ISSUE TITLE
Commit messages should use the imperative mood

### ISSUE THREAD

**Issue by ethanmad** [gitterHQ/readme-badger#14]
Currently, the automatically generated messages read "Added Gitter badge". The message _should_ be "Add Gitter badge".

See "[How to Write a Git Commit Message](http://chris.beams.io/posts/git-commit/)," specifically [tip 5](http://chris.beams.io/posts/git-commit/#imperative).

**Comment by MadLittleMods** [comment]
Good spot :)

The PR is called `Add a Gitter chat badge to README.md` but commit is `Added Gitter badge`.

**Comment by MadLittleMods** [comment]
I made a commit internally that fixes this issue.

**Comment by ethanmad** [comment]
Using imperative mood, I hope. ;) Thanks for fixing this so quickly!

**Comment by suprememoocow** [comment]
@MadLittleMods have you updated the dependency in gitter-webapp? If not, let me know, and I'll walk you through the shrinkwrap process (it's not obvious!)
