### ISSUE TITLE
gitter-badger pulled in waaay too many commits

### ISSUE THREAD

**Issue by shader** [gitterHQ/readme-badger#15]
I'm not sure exactly what went wrong, but gitter-badger's pull request at arclanguage/anarki#24 is trying to merge in several hundred commits, instead of simply adding the gitter badge.

**Comment by suprememoocow** [comment]
Hi. Sorry that this happened! Is it possible that someone created a pull-request previously when the project had a different name and then created a second PR for the badge now?

**Comment by shader** [comment]
I don't think so. As far as I know today was the first time the room was created on gitter.

Looking into it a little further, it seems that someone else on a different fork of the project may have created a gitter-badge pull request: esden/arc#1

**Comment by MadLittleMods** [comment]
Closing in favor of https://github.com/gitterHQ/readme-badger/issues/17
