### ISSUE TITLE
Consider explicitly asking the user whether they want a PR

### ISSUE THREAD

**Issue by dom96** [gitterHQ/readme-badger#19]
I just accidentally created a gitter room for one of my repos, because I clicked while the repo list was still loading...

Would be nice if you added some sort of confirm dialog for that and also the PR creation process.

**Comment by MadLittleMods** [comment]
Hey @dom96,

The create room confirmation already has an issue here: https://github.com/gitterHQ/gitter/issues/698

A confirmation for the "Send Pull Request" button sounds like a good idea.
