### ISSUE TITLE
Badger should delete fork of project once PR is merged or rejected

### ISSUE THREAD

**Issue by jamen** [gitterHQ/readme-badger#20]
I think the badger should delete the fork once the badge has been merged or rejected.

You can't even load gitter badger's page because it has so many forks or something.  GitHub displays an error.

This would probably be nice for GitHub's sake too.

**Comment by MadLittleMods** [comment]
@jamen Is the goalof this to see the badgers profile?

**Comment by jamen** [comment]
Yeah, now that you mention it there isn't really a point.  It just seems like it would be better if it did for some reason...  Oh well.
