### ISSUE TITLE
gitter-badger sent me a PR I did not request

### ISSUE THREAD

**Issue by bill-auger** [gitterHQ/readme-badger#21]
I opened the "share this chat room" modal and copied the embed url and gitter-badger sent me a PR.

**Comment by MadLittleMods** [comment]
Related to https://github.com/gitterHQ/gitter/issues/709

**Comment by MadLittleMods** [comment]
Is it possible you clicked the "Send pull request" button? Closing for now as we haven't had other reports

![](https://i.imgur.com/LaiPbYc.png)

**Comment by bill-auger** [comment]
dood - this was in 2015 - that button probably did not exists at that time - regardless, i seriously dont remember
