### ISSUE TITLE
gitter-badger should delete pull request when chatroom is deleted.

### ISSUE THREAD

**Issue by luckydonald** [gitterHQ/readme-badger#23]
If not merged yet.

**Comment by luckydonald** [comment]
Also It does't seem to remove the fork.

**Comment by MadLittleMods** [comment]
We occasionally do a clean-up of the forks to keep things loading smoothly for the badger profile.

There isn't a way to delete pull requests, see http://stackoverflow.com/a/18318431/796832

**Comment by luckydonald** [comment]
Maybe closing it is worth a consideration?

**Comment by MadLittleMods** [comment]
I think we would opt to leaving that up to the repo to decide but it is a possibility.
