### ISSUE TITLE
Quite off

### ISSUE THREAD

**Issue by sils** [gitterHQ/readme-badger#27]
https://github.com/coala-analyzer/coala-bears/pull/418

also I never asked for a PR

**Comment by MadLittleMods** [comment]
The PR comes from leaving the checkbox checked.

![](http://i.imgur.com/2ANatBf.png)

**Comment by sils1297** [comment]
Ah, I'd recommend putting that one on top so people see it, also defaulting it to false would be nice IMO.

**Comment by MadLittleMods** [comment]
The UI has changed a bit here and it seems more clear. Closing for now.

![](https://i.imgur.com/N1fnT6c.png)
