### ISSUE TITLE
Aim is off

### ISSUE THREAD

**Issue by garetmckinley** [gitterHQ/readme-badger#31]
[Mine put it inside the installation instructions](https://github.com/JSBros/hedron/pull/18). Not sure where it's supposed to go, but I feel like this isn't it.

![screen shot 2016-11-11 at 8 10 02 pm](https://cloud.githubusercontent.com/assets/1624279/20234530/db76cd50-a84a-11e6-88a8-0d941d00e4f3.png)

Since there's already a badge in my README, it would be really cool if gitter could detect this, and then place the gitter badge next to the other badges.

Just a thought.

**Comment by Felli** [comment]
I'd have to agree, the same thing happened on my side was well.
