### ISSUE TITLE
When does gitter-badger drop the fork?

### ISSUE THREAD

**Issue by fabd** [gitterHQ/readme-badger#32]
It's annoying to see "1 fork" which isn't somebody having an interest in forking my repo.

Can you please drop the repositories?

Just had a look at the gitter-badger page and it says **25.6k** repositories...

Please tell me you remove the fork after the merge is done. :-/

ps: pull request was merged 3 days ago, and the Pull Request is closed ,that should be enough of a signal for gitter-badger to drop the fork?

**Comment by MadLittleMods** [comment]
Forks are cleaned up from time to time manually.

**Comment by fabd** [comment]
Could you please delete the fork from fabd/kanji-koohii ? I genuinely did not expect the badge to work that way. Had I known I'd have added the link myself.
