### ISSUE TITLE
Aim is off

### ISSUE THREAD

**Issue by ortonomy** [gitterHQ/readme-badger#38]
https://github.com/ortonomy/flingapp/pull/2

It didn't ``\n`` at start of file, so looks it's an in-line badge -- but this has nothing to do with the text...

**Comment by JoeGannon** [comment]
Going to piggy back off of this issue... I'll create a new one if necessary. I would've liked the badge to have been placed after the nuget one (line 3 as of 33a6725). Instead, it was mixed in with the content.
