### ISSUE TITLE
Badge placement should be below existing badges

### ISSUE THREAD

**Issue by elwayman02** [gitterHQ/readme-badger#4]
Would be nice if the bot creating pull requests would detect if there were other badges in the README already (ie Travis-CI build status) and add the Gitter badge below them.

**Comment by bb010g** [comment]
Example & fix [here](https://github.com/aurapm/aura/commit/c649fabf30bad5f2af591609de319c08cef03b38).

**Comment by mappum** [comment]
Agreed, I had to close the PR and make the change manually because of this.

**Comment by DarkGigaByte** [comment]
+1

The tracking data from google in the link is also bad. IMHO

**Comment by ruyadorno** [comment]
:+1:
