### ISSUE TITLE
Just another "aim is off" issue

### ISSUE THREAD

**Issue by saiichihashimoto** [gitterHQ/readme-badger#40]
Should alongside the other badges in the README

**Comment by MadLittleMods** [comment]
@saiichihashimoto Can you link and give an example?

**Comment by saiichihashimoto** [comment]
Sure! I closed the generated pull request and made my own, so it should be easy to compare.

gitter-badger's PR: https://github.com/saiichihashimoto/mongoose-normalizr/pull/7/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
My PR: https://github.com/saiichihashimoto/mongoose-normalizr/pull/8/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
