### ISSUE TITLE
No pull request from Gitter Badger, fork is really outdated

### ISSUE THREAD

**Issue by LightWayUp** [gitterHQ/readme-badger#41]
Gitter Badger forked the repository and added a badge, but no pull request was ever opened. The fork was also never removed, making it extremely outdated (last commit in the forked repository was from 3+ years ago).

Please, if there's any chance, help remove the fork, thanks! The commit that added the badge can be found here :
https://github.com/gitter-badger/MCFreedomLauncher/commit/1ad03412aeae45d855354f532f6ae22da71bd683

( I've read in other issues that there are "clean ups" of Gitter Badger's profile, but it seems that it hasn't happened for a long time…??? )

**Comment by MadLittleMods** [comment]
@LightWayUp I have manually removed https://github.com/gitter-badger/MCFreedomLauncher :tada:
