### ISSUE TITLE
How does unsubscribe work?

### ISSUE THREAD

**Issue by schneems** [gitterHQ/readme-badger#42]
I clicked because I was curious, is it possible to resubscribe?

Also is the unsubscribe based on repos for my username or any repo that I have commit to? i.e. is it possible for an org to unsubscribe?

**Comment by MadLittleMods** [comment]
@schneems Please open an issue on https://gitlab.com/gitlab-org/gitter/webapp instead of `readme-badger` which is unrelated.

See

 - https://gitlab.com/gitlab-org/gitter/webapp/issues/893
 - https://gitlab.com/gitlab-org/gitter/webapp/issues/805
