### ISSUE TITLE
All caps in badge text feels out of place

### ISSUE THREAD

**Issue by elwayman02** [gitterHQ/readme-badger#5]
Check out this screenshot next to other common badges:

![screenshot_041315_022707_am](https://cloud.githubusercontent.com/assets/1325482/7113046/d389ee8a-e184-11e4-8558-bc7c6abdeabd.jpg)

It would be a lot better if the badge conformed to the standards of other common badges...the icons and the ALL CAPS text makes it feel a little juvenile (no offense intended), which makes me not want to associate the badge with my open-source projects.

**Comment by trevorah** [comment]
I agree. We should use shields.io (https://github.com/gitterHQ/gitter/issues/636).

**Comment by troyswanson** [comment]
:+1:

**Comment by n1trux** [comment]
:+1: for shields.io

**Comment by trevorah** [comment]
We're now using the standard. All existing badges should update.
