### ISSUE TITLE
Optional PR?

### ISSUE THREAD

**Issue by grrowl** [gitterHQ/readme-badger#7]
Would be great for Gitter itself to ask "Do you want to create a PR to add a badge to this repo?" — accidental clicking can randomly create PRs in otherwise quiet repos.

**Comment by mydigitalself** [comment]
There's a checkbox at the bottom of the room creation confirmation for exactly this, or am I missing something?

**Comment by mydigitalself** [comment]
![screen shot 2015-06-02 at 08 50 24](https://cloud.githubusercontent.com/assets/1491887/7930927/78f2b68a-0904-11e5-808f-1b70c59a88f6.png)

**Comment by grrowl** [comment]
Yes, this is true. I am so sorry.

![screen shot 2015-06-02 at 17 53 01](https://cloud.githubusercontent.com/assets/907140/7930989/4ed53458-0950-11e5-9140-55ca13b7386f.png)

**Comment by mydigitalself** [comment]
No problem, happens to the best of us :)
