### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by n1trux** [gitterHQ/readme-badger#9]
I think you should include a simple additional line break at the end because it looks way better when the badge is above the rest of the text. In this issue this renders properly, but usually a single line break in Markdown doesn't mean a new paragraph.
## How it should not look

https://github.com/gitter-badger/awesome-sysadmin/blob/gitter-badge/README.md

```
[![Join the chat at https://gitter.im/n1trux/awesome-sysadmin](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/n1trux/awesome-sysadmin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
**A curated list of amazingly awesome open source sysadmin resources.** You can check out [other awesome lists](https://github.com/sindresorhus/awesome) as well. Please read [CONTRIBUTING](./CONTRIBUTING.md) if you wish to add software.
```

renders like this:

[![Join the chat at https://gitter.im/n1trux/awesome-sysadmin](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/n1trux/awesome-sysadmin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) **A curated list of amazingly awesome open source sysadmin resources.** You can check out [other awesome lists](https://github.com/sindresorhus/awesome) as well. Please read [CONTRIBUTING](./CONTRIBUTING.md) if you wish to add software.
## how it should look

[![Join the chat at https://gitter.im/n1trux/awesome-sysadmin](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/n1trux/awesome-sysadmin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**A curated list of amazingly awesome open source sysadmin resources.** You can check out [other awesome lists](https://github.com/sindresorhus/awesome) as well. Please read [CONTRIBUTING](./CONTRIBUTING.md) if you wish to add software.

---

notice the additional line break before "A curated list [...]".

**Comment by kanekotic** [comment]
i agree :). I was going to report exactly the same.

**Comment by tomkerkhove** [comment]
Same here!

**Comment by ChALkeR** [comment]
Same here: https://github.com/qmlweb/qmlweb/pull/11

**Comment by Zoltu** [comment]
Another example of no newline: https://github.com/Zoltu/Gradle.Plugin.Versioning/pull/10/files

**Comment by wafflestealer654** [comment]
Agreed. I received a pull request with no newline. It doesn't look good having the badge to the left of the text.

Example: https://github.com/wafflestealer654/google-maps-3d-client/pull/5/commits/c32b8b23278f7e8156f681aff37ecc5ad0e5c248

A simple `\n` at the end of the inserted text should suffice.

**Comment by johncarl81** [comment]
One detail to take into account, if there are already badges on the page, adding a newline will cause the badges to break up unnaturally, at least with Asciidoc:

Fixed:

And the fixing commit: https://github.com/johncarl81/transfuse/commit/2d032a0f1ed41f70b6877e67c7fb63917f193c9d
